BEGIN;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS source_hash VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE advertisements ADD COLUMN IF NOT EXISTS source_hash VARCHAR(64) NOT NULL DEFAULT '';
COMMIT;
